# Generated by Django 2.0.6 on 2018-06-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.CharField(max_length=8)),
                ('user_name', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('create_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
